version: '3.4'
services:
  bootnode:
    build:
      dockerfile: ./images/lighthouse.Dockerfile
    expose:
      - 4242/tcp
      - 4242/udp
    volumes:
      - ./genesis_data:/data
      - ./genesis_config:/config
      - ./scripts:/scripts
    entrypoint:
      "/scripts/bootnode.sh"
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
  genesis-generator:
    image: ethpandaops/ethereum-genesis-generator:latest
    entrypoint: 
      "/scripts/genesis_generator.sh"
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./validator_data:/validator_data
      - ./genesis_config:/config
    expose:
      - 8000
  beacon:
    build:
      dockerfile: ./images/lighthouse.Dockerfile
    deploy:
      replicas: 2 # TODO use env var NUM_NODES
    expose:
      - 5052
      - 9000/tcp
      - 9000/udp
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
    entrypoint:
      "/scripts/beacon.sh"
    depends_on:
      bootnode:
        condition: service_started
  execution:
    image: ethereum/client-go
    deploy:
      replicas: 2
    expose:
      - 8545
      - 8551
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./genesis_config:/config
    entrypoint:
      "/scripts/execution.sh"
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
  validator:
    build:
      dockerfile: ./images/lighthouse.Dockerfile
    deploy:
      replicas: 2
    expose:
      - 5052
    volumes:
      - ./scripts:/scripts
      - ./genesis_data:/data
      - ./validator_data/node_1:/validator_data
    entrypoint:
      "/scripts/validator.sh"
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
  proxy:
    image: seananderson33/json_rpc_snoop:capella
    deploy:
      replicas: 2
    entrypoint:
      "/scripts/proxy.sh"
    expose:
      - 8551
    volumes:
      - ./scripts:/scripts

